# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiptrader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
