# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiptrader', '0003_auto_20190313_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='name',
        ),
        migrations.AddField(
            model_name='starship',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
