# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiptrader', '0004_auto_20190313_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starship',
            name='cargo_capacity',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='starship',
            name='crew',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='starship',
            name='hyperdrive_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='starship',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='starship',
            name='passengers',
            field=models.IntegerField(null=True),
        ),
    ]
